[package]
name = "resty"
version = "0.1.0"
authors = ["Tomasz Drwięga <tomusdrw@gmail.com>"]

[dependencies]
arrayvec = "0.4"
futures = "0.1"
hyper = "0.11"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
